"""Phase 1 validation dashboard page.

Displays the validation report generated by `scripts/run_validation.py`:
1. Gate result (pass/fail with market breakdown)
2. Pivot hit-rate comparison bar chart
3. Pivot detail table
4. Forward-return scatter plots per market
5. Zone-distribution heatmap

Consumes `scripts/validation_report.json` via `validation_data.py`.
"""

from __future__ import annotations

import streamlit as st

from finsynapse.dashboard import charts
from finsynapse.dashboard.i18n import SUPPORTED, t
from finsynapse.dashboard.validation_data import load_report

DEFAULT_LANG = "zh"


def main() -> None:
    st.set_page_config(page_title=t("section_validation", DEFAULT_LANG), layout="wide", page_icon="📊")

    lang = "zh"
    with st.sidebar:
        lang = st.radio(
            "语言 / Language",
            options=list(SUPPORTED),
            index=list(SUPPORTED).index(DEFAULT_LANG),
            format_func=lambda c: {"zh": "中文", "en": "English"}[c],
            horizontal=True,
        )

    report = load_report()
    if report is None:
        st.warning(t("val_no_report", lang))
        st.stop()

    st.title(f"📊 {t('section_validation', lang)}")
    st.caption(
        t("val_report_meta", lang).format(
            date=report.generated,
            evaluated=report.pivots_evaluated,
            total=report.pivots_total,
        )
    )

    # --- Gate ---
    st.subheader(t("val_section_gate", lang))
    if report.gate is not None:
        if report.gate_passed:
            st.success(t("val_gate_passed", lang).format(n=report.gate.markets_beaten, total=report.gate.total_markets))
        else:
            st.error(t("val_gate_failed", lang).format(n=report.gate.markets_beaten, total=report.gate.total_markets))
        st.caption(report.gate.standard)

        with st.expander("Gate per-market details", expanded=False):
            for mkt, detail in report.gate.details.items():
                status = "✓" if detail.get("beaten") else "✗"
                st.text(
                    f"{status} {mkt.upper()}: "
                    f"MF={detail.get('mf_directional_rate', 0):.1%} vs "
                    f"PE={detail.get('pe_directional_rate', 0):.1%}"
                )

    st.divider()

    # --- Pivot validation ---
    st.subheader(t("val_section_pivots", lang))

    hit_col, _ = st.columns([2, 1])
    with hit_col:
        st.plotly_chart(
            charts.validation_hit_rate_bar(report.hit_rate_table, lang),
            use_container_width=True,
        )

    # Pivot detail table — convert dataclasses to dicts for Plotly
    pivot_dicts = [
        {
            "label": pr.label,
            "market": pr.market,
            "date": pr.date,
            "expected_zone": pr.expected_zone,
            "controllers": [
                {
                    "name": c.name,
                    "overall": c.overall,
                    "zone": c.zone,
                    "strict_pass": c.strict_pass,
                    "directional_pass": c.directional_pass,
                }
                for c in pr.controllers
            ],
        }
        for pr in report.pivot_results
    ]
    st.plotly_chart(
        charts.validation_pivot_table(pivot_dicts, lang),
        use_container_width=True,
    )

    st.divider()

    # --- Forward predictive power ---
    st.subheader(t("val_section_forward", lang))

    # Spearman ρ summary
    if report.spearman_rho:
        cols = st.columns(3)
        for col, market in zip(cols, ["us", "cn", "hk"], strict=True):
            with col:
                st.markdown(f"**{market.upper()}**")
                m_data = report.spearman_rho.get(market, {})
                for label in ["1m", "3m", "6m", "12m"]:
                    rho = m_data.get(label)
                    if rho is not None:
                        color = "#10B981" if abs(rho) > 0.1 else ("#F87171" if abs(rho) < 0.03 else "#FBBF24")
                        st.markdown(
                            f"- {label}: <span style='color:{color};font-weight:600'>{rho:+.3f}</span>",
                            unsafe_allow_html=True,
                        )
                    else:
                        st.markdown(f"- {label}: N/A")

    # Forward scatter plots
    forward_rows = []
    for pr in report.pivot_results:
        forward_rows.append(
            {
                "temperature": next((c.overall for c in pr.controllers if c.name == "multi-factor"), 0),
                "market": pr.market,
            }
        )
    # For forward scatter we use the zone distribution data; synthesize row-level data
    # from the pivot temperatures for scatter display
    scatter_market = st.radio(
        "Market",
        options=["us", "cn", "hk"],
        horizontal=True,
        format_func=lambda m: m.upper(),
        label_visibility="collapsed",
    )
    scatter_horizon = st.radio(
        "Horizon",
        options=["1m", "3m", "6m", "12m"],
        horizontal=True,
        index=1,
        label_visibility="collapsed",
    )

    # Build synthetic forward rows from pivot data for scatter
    syn_rows = [
        {
            "market": r["market"],
            "temperature": r["temperature"],
            "return_1m": None,
            "return_3m": None,
            "return_6m": None,
            "return_12m": None,
        }
        for r in forward_rows
    ]
    st.plotly_chart(
        charts.validation_forward_scatter(syn_rows, scatter_market, scatter_horizon, lang),
        use_container_width=True,
    )
    st.caption("Note: scatter shows pivot-point temperatures only. Full forward-return analysis in zone heatmap below.")

    st.divider()

    # Zone heatmap
    st.subheader(t("val_zone_distribution", lang))
    st.plotly_chart(
        charts.validation_zone_heatmap(report.zone_distribution, lang),
        use_container_width=True,
    )

    st.divider()

    # --- External anchor (CNN F&G) ---
    ext = report.external_anchor
    if ext is not None and isinstance(ext, dict):
        st.subheader(t("val_anchor_section", lang))
        st.caption(ext.get("source", ""))
        pivot_comp = ext.get("pivot_comparison", [])
        if pivot_comp:
            alignment = ext.get("direction_agreement", {})
            st.metric(
                f"{t('val_anchor_title', lang)} — {t('val_anchor_section', lang)}",
                f"{alignment.get('aligned', 0)}/{alignment.get('total', 0)} aligned",
            )
            st.plotly_chart(
                charts.external_anchor_comparison(pivot_comp, lang),
                use_container_width=True,
            )
        corr = ext.get("correlation")
        if corr:
            st.caption(
                f"Spearman ρ = {corr['spearman_rho']:+.3f} (p={corr['p_value']:.6f}, n={corr['n']})"
            )

    # Bootstrap CI summary
    bs = report.bootstrap_ci
    if bs is not None and isinstance(bs, dict):
        with st.expander(t("val_bootstrap_ci", lang), expanded=False):
            for mkt, ci in bs.items():
                st.text(f"{mkt.upper()}: mean band width = {ci['mean_band_width']:.1f}°")


if __name__ == "__main__":
    main()
