"""Load and cache the Phase 1 validation report for the dashboard.

The report is generated by `scripts/run_validation.py` and stored as
`scripts/validation_report.json`. This module loads it into typed
dataclasses for the Streamlit page and static renderer.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

REPORT_PATH = Path("scripts/validation_report.json")


@dataclass
class ControllerResultData:
    name: str
    overall: float
    zone: str
    strict_pass: bool
    directional_pass: bool
    valuation: float | None = None
    sentiment: float | None = None
    liquidity: float | None = None


@dataclass
class PivotResultData:
    label: str
    market: str
    date: str
    expected_zone: str
    controllers: list[ControllerResultData] = field(default_factory=list)


@dataclass
class HitRateMarket:
    total: int
    directional_hits: int
    directional_rate: float
    strict_hits: int
    strict_rate: float


@dataclass
class ForwardStat:
    n: int = 0
    mean: float = 0.0
    spearman_rho: float | None = None


@dataclass
class ZoneBucket:
    horizon: str
    mean_return: float | None
    median_return: float | None
    win_rate: float | None
    n: int


@dataclass
class GateResult:
    passed: bool
    markets_beaten: int
    total_markets: int
    standard: str
    details: dict = field(default_factory=dict)


@dataclass
class ValidationReport:
    version: str
    generated: str
    pivots_total: int
    pivots_evaluated: int
    pivot_results: list[PivotResultData] = field(default_factory=list)
    hit_rate_table: dict = field(default_factory=dict)
    forward_stats: dict = field(default_factory=dict)
    zone_distribution: dict = field(default_factory=dict)
    spearman_rho: dict = field(default_factory=dict)
    gate: GateResult | None = None
    external_anchor: dict | None = None
    bootstrap_ci: dict | None = None

    @property
    def gate_passed(self) -> bool:
        return self.gate is not None and self.gate.passed


def _parse_pivot_result(raw: dict) -> PivotResultData:
    controllers = [
        ControllerResultData(
            name=c["name"],
            overall=c["overall"],
            zone=c["zone"],
            strict_pass=c["strict_pass"],
            directional_pass=c["directional_pass"],
            valuation=c.get("valuation"),
            sentiment=c.get("sentiment"),
            liquidity=c.get("liquidity"),
        )
        for c in raw.get("controllers", [])
    ]
    return PivotResultData(
        label=raw["label"],
        market=raw["market"],
        date=raw["date"],
        expected_zone=raw["expected_zone"],
        controllers=controllers,
    )


def _parse_gate(raw: dict) -> GateResult:
    return GateResult(
        passed=raw["passed"],
        markets_beaten=raw["markets_beaten"],
        total_markets=raw["total_markets"],
        standard=raw["standard"],
        details=raw.get("details", {}),
    )


def load_report(path: Path | None = None) -> ValidationReport | None:
    p = path or REPORT_PATH
    if not p.exists():
        return None
    with p.open() as f:
        raw = json.load(f)
    return ValidationReport(
        version=raw.get("version", "0.0.0"),
        generated=raw.get("generated", ""),
        pivots_total=raw.get("pivots_total", 0),
        pivots_evaluated=raw.get("pivots_evaluated", 0),
        pivot_results=[_parse_pivot_result(pr) for pr in raw.get("pivot_results", [])],
        hit_rate_table=raw.get("hit_rate_table", {}),
        forward_stats=raw.get("forward_stats", {}),
        zone_distribution=raw.get("zone_distribution", {}),
        spearman_rho=raw.get("spearman_rho", {}),
        gate=_parse_gate(raw["gate"]) if "gate" in raw else None,
        external_anchor=raw.get("external_anchor"),
        bootstrap_ci=raw.get("bootstrap_ci"),
    )
